version: '3'

services:
  mariadb:
    build:
      context: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/data.sql
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites:/etc/nginx/sites-available
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - 8080:80
  php-fpm:
    build:
      context: ./docker/php-fpm # eklentiler icin kendimiz build ediyoruz
    volumes:
      - .:/var/www # nginx ile ayni dosyalara erisim
    depends_on: # diger containerlara isimleri ile erisim
      - mariadb
      - redis
  redis:
    image: 'redis'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
